var listOfMotivationQuotes: MutableList<String> = mutableListOf(
    "Erfolg ist kein Zufall, sondern das Ergebnis harter Arbeit und Entschlossenheit",
    "Glück ist, was passiert, wenn Vorbereitung auf Gelegenheit trifft.",
    "Wer aufgibt, hat schon verloren. Wer kämpft, hat schon gewonnen.",
    "Gib niemals auf, denn jeder Fehler ist eine Chance, zu lernen und zu wachsen.",
    "Dein größter Konkurrent bist du selbst. Überwinde dich selbst und du wirst unbesiegbar sein.",
    "Der erste Schritt zu einem erfolgreichen Leben ist die Entscheidung, etwas zu unternehmen.",
    "Konzentrieren Sie sich auf Ihre Ziele, ignorieren Sie alle Ablenkungen und bleiben Sie motiviert.",
    "Erfolg ist nicht endgültig, Niederlagen sind nicht tödlich: Es ist der Mut, der zählt.",
    "Wenn du bereit bist, hart zu arbeiten und Risiken einzugehen, kannst du deine Träume verwirklichen",
    "Jeder Mensch hat das Potenzial für Großes, aber es liegt an uns, es zu entfesseln",
    "Ein Mensch, der noch nie einen Fehler gemacht hat, hat noch nie etwas Neues ausprobiert",
    "Mach jeden Tag zu einem wichtigen Tag, denn ein Tag kann dein Leben verändern",
    "Der Erfolg ist nicht endgültig, die Niederlage ist nicht schlimm: Es ist der Mut, der zählt.",
    "Das Ziel ist nicht, schnell zu sein, sondern besser zu werden.",
    "Glaube an dich selbst und alles andere wird sich von selbst ergeben",
    "Ein erfolgreiches Leben beginnt mit einer klaren Vision und dem Mut, sie zu verfolgen",
    "Das größte Hindernis auf dem Weg zum Erfolg ist die Angst vor dem Scheitern.",
    "Der erste und wichtigste Schritt zum Erfolg ist die Entscheidung, ihn zu wollen.",
    "Ändere deine Gedanken, ändere dein Leben.",
    "Harte Arbeit besiegt das Talent, wenn das Talent nicht hart arbeitet.",
    "Lass deine Träume größer sein als deine Ängste.",
    "Werde nicht müde, gute Dinge zu tun, denn bald wirst du die Früchte ernten.",
    "Jeder kann Großes erreichen, wenn er nicht darauf achtet, wer die Schuld dafür bekommt.",
    "Es kommt nicht darauf an, wo du jetzt bist, sondern wohin du gehst",
    "Der erfolgreichste Weg ist immer dein eigener.",
    "Verfolge deine Leidenschaft und das Geld wird dir folgen.",
    "Wenn du deine Ziele kennst, brauchst du die Meinung anderer nicht",
    "Wenn du etwas willst, wirst du einen Weg finden. Wenn du etwas nicht willst, wirst du eine Ausrede finden.",
    "Deine Einstellung bestimmt deine Höhe",
    "Wer einen Schritt zurückgeht, um zwei Schritte vorwärts zu machen, ist im Vorteil",
    "Jeder ist ein Meister, solange er übt.",
    "Wenn du erfolgreich sein willst, musst du bereit sein, außerhalb deiner Komfortzone zu arbeiten.",
    "Ein Ziel ohne Plan ist nur ein Wunsch.",
    "Lass dich nicht von der Vergangenheit bestimmen, sondern lass dich von ihr lehren.",
    "Erfolg kommt nicht vom Warten, sondern vom Tun.",
    "Eine positive Einstellung kann Berge versetzen",
    "Der erfolgreichste Mensch ist derjenige, der am meisten aus seinen Fehlern lernt",
    "Gib niemals auf, denn jeder Misserfolg ist ein Schritt näher zum Erfolg",
    "Erfolg ist eine Reise, kein Ziel.",
    "Denken Sie groß, handeln Sie mutig, bleiben Sie konzentriert und erreichen Sie Ihre Ziele.",
    "Ein Leben ohne Ziele ist wie ein Schiff ohne Kompass.",
    "Lassen Sie sich von niemandem unter Druck setzen, nur Sie wissen, was Sie wirklich wollen.",
    "Eine gute Vorbereitung ist der Grundstein für jeden Erfolg.",
    "Sei bereit, hart zu arbeiten und Risiken einzugehen, um deine Träume zu verwirklichen.",
    "Behalte deine Ziele im Auge und ignoriere alle Ablenkungen.",
    "Erfolg kommt durch Kontinuität, also geben Sie nicht auf.",
    "Eine Vision und das Vertrauen in deine Fähigkeiten können dich zu Großem führen.",
    "Geben Sie nicht auf, denn jeder Misserfolg ist eine Chance, sich zu verbessern.",
    "Jeder kann erfolgreich sein, wenn er bereit ist, hart dafür zu arbeiten."
)

var userName: String = ""